server:
  port: 4000

spring:
  application:
    name: registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

---
spring:
  profiles:
    active: local

eureka:
  instance:
    hostname: localhost

---
spring:
  profiles:
    active: prod

eureka:
  instance:
    hostname: 172.18.94.65