version: '3'

services:
  registry-app:
    restart: "on-failure"
    image: "logistics-registry-app:0.0.1"                     # 镜像名：标签名
    hostname: registry                                        # 注册中心的hostname一定要有，且必须和代码中配置文件里的hostname一致
    networks:
      - app-net                                               # 加入的网络
    ports:
      - 4000:4000                                             # 映射的端口号，和代码中配置文件里的端口号一致
    container_name: registry-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}       # spring-boot环境
  gateway-app:
    restart: "on-failure"
    image: "logistics-gateway-app:0.0.1"
    hostname: registry
    networks:
      - app-net
    ports:
      - 5000:5000
    container_name: gateway-app
    depends_on:
      - registry-app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  order-app:
    restart: "on-failure"
    image: "logistics-order-app:0.0.1"
    hostname: registry
    networks:
      - app-net
    ports:
      - 6000:6000
    container_name: order-app
    depends_on:
      - registry-app
      - gateway-app
      - mysql
    links:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
  mysql:
    restart: "on-failure"
    image: mysql:8.0.23
    networks:
      - app-net
    ports:
      - 3306:3306
    container_name: mysql
    volumes:
      - ${DOCKER_DIR}/var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  redis:
    restart: "on-failure"
    image: redis:6.2.1
    networks:
      - app-net
    ports:
      - 6379:6379
    container_name: redis
    volumes:
      - ${DOCKER_DIR}/data:/data

networks:
  app-net:
    driver: bridge