server:
  port: 6050
  servlet:
    context-path: /order

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${eureka.instance.hostname}:3306/test?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&createDatabaseIfNotExist=true
    username: root
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:4000/eureka