server:
  port: 6050
  servlet:
    context-path: /order

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${eureka.instance.hostname}:3306/logistics_order?useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: ${db.root.password}
    type: com.alibaba.druid.pool.DruidDataSource
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: ${eureka.instance.hostname}
  rabbitmq:
    addresses: ${eureka.instance.hostname}:5672
    username: root
    password: ${db.root.password}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}/actuator
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:4000/eureka

db:
  root:
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full

info:
  app:
    author: Simon
    source-encoding: @project.build.sourceEncoding@
    jdk: @java.version@

logging:
  file:
    path: /logs/${spring.application.name}