server:
  port: 6000
  servlet:
    context-path: /order

spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&createDatabaseIfNotExist=true
    username: root
    password: jiangqingyuan
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4000/eureka/