server:
  port: 5050
  servlet:
    context-path: /account

spring:
  application:
    name: account
  redis:
    host: ${eureka.instance.hostname}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:4000/eureka