server:
  port: 5000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:4000/eureka/

---
spring:
  profiles:
    active: local

eureka:
  instance:
    hostname: localhost

---
spring:
  profiles:
    active: prod

eureka:
  instance:
    hostname: 172.18.94.65